In [84]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

from keras.models import Sequential
from keras.layers import Dense

In [37]:
df = pd.read_csv('Fraud Detection.csv')

In [38]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [39]:
X = df.iloc[ : , 3:13].values
y = df.iloc[ : , 13:].values

## Changing Counteirs into Number

In [42]:
lbl_encoder = LabelEncoder()
X[:,1] = lbl_encoder.fit_transform(X[:,1])

In [44]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

## Changing Genders into Number

In [48]:
lbl_encoder = LabelEncoder()
X[:,2] = lbl_encoder.fit_transform(X[:,2])

In [47]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [50]:
X[0]

array([619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

## Standardise the Values

In [53]:
scaler = StandardScaler()

X = scaler.fit_transform(X)

/opt/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [59]:
X[1]

array([-0.44003595,  1.51506738, -1.09598752,  0.19816383, -1.38753759,
        0.11735002, -0.91158349, -1.54776799,  0.97024255,  0.21653375])

## Train Test Split
### 80% - Training
### 10% - Testing
### 10% - Validation

In [64]:
X_train, X_test, y_train, y_test  = train_test_split(X,y, test_size = 0.2)

In [69]:
X_test, X_val, y_test, y_val  = train_test_split(X_test,y_test, test_size = 0.5)

In [70]:
X.shape

(10000, 10)

In [71]:
X_train.shape

(8000, 10)

In [72]:
X_test.shape

(1000, 10)

In [73]:
X_val.shape

(1000, 10)

## Build Neural Network

In [90]:
model = Sequential()

model.add(Dense(6 , activation = 'relu', input_dim = 10))
model.add(Dense(6 , activation = 'relu'))

model.add(Dense(1, activation = 'sigmoid'))

model.compile( optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [91]:
model.fit(X_train, y_train, epochs = 30, validation_data = (X_val, y_val))

Train on 8000 samples, validate on 1000 samples
Epoch 1/30
8000/8000 [==============================] - 1s 151us/step - loss: 0.6979 - accuracy: 0.5765 - val_loss: 0.5675 - val_accuracy: 0.7810
Epoch 2/30
8000/8000 [==============================] - 1s 88us/step - loss: 0.5039 - accuracy: 0.7980 - val_loss: 0.4890 - val_accuracy: 0.7960
Epoch 3/30
8000/8000 [==============================] - 1s 87us/step - loss: 0.4490 - accuracy: 0.8027 - val_loss: 0.4467 - val_accuracy: 0.8000
Epoch 4/30
8000/8000 [==============================] - 1s 92us/step - loss: 0.4190 - accuracy: 0.8108 - val_loss: 0.4251 - val_accuracy: 0.8110
Epoch 5/30
8000/8000 [==============================] - 1s 100us/step - loss: 0.4013 - accuracy: 0.8179 - val_loss: 0.4118 - val_accuracy: 0.8250
Epoch 6/30
8000/8000 [==============================] - 1s 107us/step - loss: 0.3894 - accuracy: 0.8260 - val_loss: 0.4034 - val_accuracy: 0.8350
Epoch 7/30
8000/8000 [==============================] - 1s 96us/step - loss: 0.

In [92]:
model.evaluate(X_test, y_test)

1000/1000 [==============================] - 0s 59us/step


[0.374695228099823, 0.8420000076293945]

In [93]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [97]:
df.head(1)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [104]:
lst = df.head(1).values[0]

In [108]:
lst[3:-1]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [137]:
data = np.array([[502, 0, 0, 42,8,159660.0,3,1,0,113931.88]])
data = scaler.transform(data)

pred = model.predict(data)

if (pred[0][0] > .5):
    print("Fraud")
else:
    print("Not")

Fraud


In [139]:
pred

array([[0.9823267]], dtype=float32)